"""Inloggning för mobilappen.

Användare lagras i tabellen app_users (skapas av ensure_auth_schema).
Lösenord hashas med scrypt (standardbiblioteket - inga extra paket).
Efter inloggning får appen en slumpad token som skickas som
"Authorization: Bearer <token>" i alla anrop. Token lagras i app_sessions.
"""

import hashlib
import os
import secrets
from datetime import datetime, timedelta, timezone

from fastapi import Depends, HTTPException, Request, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from psycopg.rows import dict_row

# Hur länge en inloggning gäller utan aktivitet. Varje anrop förlänger.
SESSION_DAYS = int(os.environ.get("SESSION_DAYS", "30"))

_bearer = HTTPBearer(auto_error=False)


def ensure_auth_schema(conn):
    with conn.cursor() as cur:
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS app_users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT NOT NULL UNIQUE,
                display_name TEXT,
                password_salt TEXT NOT NULL,
                password_hash TEXT NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS app_sessions (
                token TEXT PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
                device_name TEXT,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                expires_at TIMESTAMP NOT NULL
            )
            """
        )
        cur.execute(
            "CREATE INDEX IF NOT EXISTS idx_app_sessions_user_id ON app_sessions(user_id)"
        )


# ---------------------------------------------------------------- lösenord

def _hash_password(password: str, salt_hex: str) -> str:
    digest = hashlib.scrypt(
        password.encode("utf-8"),
        salt=bytes.fromhex(salt_hex),
        n=2 ** 14,
        r=8,
        p=1,
        dklen=32,
    )
    return digest.hex()


def make_password(password: str):
    """Returnerar (salt_hex, hash_hex) för lagring."""
    salt_hex = secrets.token_hex(16)
    return salt_hex, _hash_password(password, salt_hex)


def verify_password(password: str, salt_hex: str, hash_hex: str) -> bool:
    return secrets.compare_digest(_hash_password(password, salt_hex), hash_hex)


# ---------------------------------------------------------------- användare

def create_user(conn, username: str, password: str, display_name: str = None):
    username = username.strip().lower()
    if not username or not password:
        raise ValueError("Användarnamn och lösenord måste anges.")
    if len(password) < 8:
        raise ValueError("Lösenordet måste vara minst 8 tecken.")
    salt, pw_hash = make_password(password)
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            """
            INSERT INTO app_users (username, display_name, password_salt, password_hash)
            VALUES (%s, %s, %s, %s)
            ON CONFLICT (username) DO UPDATE
            SET display_name = EXCLUDED.display_name,
                password_salt = EXCLUDED.password_salt,
                password_hash = EXCLUDED.password_hash,
                is_active = TRUE
            RETURNING id, username, display_name
            """,
            (username, display_name or username, salt, pw_hash),
        )
        return cur.fetchone()


def deactivate_user(conn, username: str):
    with conn.cursor() as cur:
        cur.execute(
            "UPDATE app_users SET is_active = FALSE WHERE username = %s",
            (username.strip().lower(),),
        )
        cur.execute(
            """
            DELETE FROM app_sessions
            WHERE user_id IN (SELECT id FROM app_users WHERE username = %s)
            """,
            (username.strip().lower(),),
        )
        return cur.rowcount


def list_users(conn):
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            "SELECT id, username, display_name, is_active, created_at FROM app_users ORDER BY username"
        )
        return cur.fetchall()


# ---------------------------------------------------------------- sessioner

def login(conn, username: str, password: str, device_name: str = None):
    """Returnerar {"token", "user"} eller kastar ValueError vid fel uppgifter."""
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            """
            SELECT id, username, display_name, password_salt, password_hash, is_active
            FROM app_users
            WHERE username = %s
            """,
            (username.strip().lower(),),
        )
        user = cur.fetchone()

    if not user or not user["is_active"] or not verify_password(
        password, user["password_salt"], user["password_hash"]
    ):
        raise ValueError("Fel användarnamn eller lösenord.")

    token = secrets.token_urlsafe(32)
    expires = datetime.now(timezone.utc).replace(tzinfo=None) + timedelta(days=SESSION_DAYS)
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO app_sessions (token, user_id, device_name, expires_at)
            VALUES (%s, %s, %s, %s)
            """,
            (token, user["id"], device_name, expires),
        )

    return {
        "token": token,
        "user": {
            "id": user["id"],
            "username": user["username"],
            "display_name": user["display_name"],
        },
    }


def logout(conn, token: str):
    with conn.cursor() as cur:
        cur.execute("DELETE FROM app_sessions WHERE token = %s", (token,))


def resolve_token(conn, token: str):
    """Returnerar användaren för en giltig token, annars None. Förlänger sessionen."""
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            """
            SELECT s.token, s.expires_at, u.id, u.username, u.display_name, u.is_active
            FROM app_sessions s
            JOIN app_users u ON u.id = s.user_id
            WHERE s.token = %s
            """,
            (token,),
        )
        row = cur.fetchone()

    if not row or not row["is_active"]:
        return None

    now = datetime.now(timezone.utc).replace(tzinfo=None)
    if row["expires_at"] < now:
        with conn.cursor() as cur:
            cur.execute("DELETE FROM app_sessions WHERE token = %s", (token,))
        return None

    new_expires = now + timedelta(days=SESSION_DAYS)
    with conn.cursor() as cur:
        cur.execute(
            """
            UPDATE app_sessions
            SET last_seen_at = CURRENT_TIMESTAMP, expires_at = %s
            WHERE token = %s
            """,
            (new_expires, token),
        )

    return {"id": row["id"], "username": row["username"], "display_name": row["display_name"]}


# ---------------------------------------------------------------- FastAPI-beroende

def current_user(
    request: Request,
    creds: HTTPAuthorizationCredentials = Depends(_bearer),
):
    """Används som Depends(current_user) på alla skyddade endpoints."""
    if creds is None or not creds.credentials:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Inloggning krävs.",
            headers={"WWW-Authenticate": "Bearer"},
        )

    pool = request.app.state.pool
    with pool.connection() as conn:
        user = resolve_token(conn, creds.credentials)

    if not user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Sessionen är ogiltig eller har gått ut. Logga in igen.",
            headers={"WWW-Authenticate": "Bearer"},
        )

    request.state.token = creds.credentials
    return user
