import os
import sys
from pathlib import Path
from dotenv import load_dotenv
import psycopg
from psycopg.rows import dict_row, tuple_row


def _app_dir() -> Path:
    # När programmet är byggt till en .exe (PyInstaller) pekar sys.executable
    # på .exe-filen själv - vi vill leta efter .env bredvid DEN, oavsett
    # varifrån programmet råkar startas (t.ex. en genväg med annan
    # "Start in"-mapp). Körs det som vanlig .py-fil används skriptets
    # egen mapp istället.
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent
    return Path(__file__).resolve().parent


APP_DIR = _app_dir()
_ENV_PATH = APP_DIR / ".env"
load_dotenv(dotenv_path=_ENV_PATH)

DATABASE_URL = os.environ.get("DATABASE_URL")


def _database_url() -> str:
    # Kontrollen görs här, vid anslutning, istället för vid import. Då kan den
    # som öppnar fönstret visa felet i en vanlig dialogruta, istället för att
    # programmet kraschar innan något fönster ens finns.
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError(
            f"Hittade ingen DATABASE_URL. Kontrollera att filen '.env' finns i: {_app_dir()}"
        )
    return url


def get_connection(use_dict_row: bool = False):
    # autocommit=True: varje sats committas direkt när den är klar, så en
    # anslutning som bara väntar (t.ex. ett öppet Lager-fönster) håller inga
    # lås i databasen. Det som måste ske "allt eller inget" lindas in i
    # "with conn.transaction():" - se t.ex. generate_article_number.
    url = _database_url()
    if use_dict_row:
        return psycopg.connect(url, autocommit=True, row_factory=dict_row)
    return psycopg.connect(url, autocommit=True)


def ensure_alive(conn, use_dict_row: bool = False):
    try:
        conn.execute("SELECT 1")
        return conn
    except Exception:
        try:
            conn.close()
        except Exception:
            pass
        return get_connection(use_dict_row=use_dict_row)


def ensure_schema(conn):
    # ALTER TABLE nedan behöver exklusivt lås på tabellen. Om någon annan
    # håller ett lås vill vi hellre få ett tydligt fel efter några sekunder
    # än ett program som hänger sig. Anslutningen kör med autocommit, så
    # inställningen gäller sessionen tills RESET längst ner i funktionen.
    conn.execute("SET lock_timeout = '5s'")

    with conn.cursor() as cur:
        cur.execute("""
        CREATE TABLE IF NOT EXISTS counters (
            prefix TEXT PRIMARY KEY,
            last INTEGER NOT NULL
        )
        """)

        cur.execute("""
        CREATE TABLE IF NOT EXISTS used_numbers (
            article_number TEXT PRIMARY KEY,
            prefix TEXT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """)

        cur.execute("""
        CREATE INDEX IF NOT EXISTS idx_used_prefix
        ON used_numbers(prefix)
        """)

        cur.execute("""
        CREATE TABLE IF NOT EXISTS sub_categories (
            k INTEGER NOT NULL,
            uu TEXT NOT NULL,
            name TEXT NOT NULL,
            PRIMARY KEY (k, uu)
        )
        """)

        cur.execute("""
        CREATE TABLE IF NOT EXISTS inventory_items (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_name TEXT NOT NULL,
            main_category TEXT,
            vehicle_brand TEXT,
            product_brand TEXT,
            barcode TEXT,
            org_article_no TEXT,
            oem TEXT,
            quantity INTEGER NOT NULL DEFAULT 0,
            unit_cost DOUBLE PRECISION,
            currency TEXT,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP,
            article_number TEXT,
            shelf_location TEXT
        )
        """)

        cur.execute("""
        ALTER TABLE inventory_items
        ADD COLUMN IF NOT EXISTS shelf_location TEXT
        """)

        cur.execute("""
        ALTER TABLE inventory_items
        ADD COLUMN IF NOT EXISTS last_inventory_check DATE
        """)

        cur.execute("""
        DO $$
        DECLARE
            seq_name TEXT := 'inventory_items_id_seq';
            has_default BOOLEAN := FALSE;
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_name = 'inventory_items'
                  AND column_name = 'id'
            ) THEN
                SELECT column_default IS NOT NULL
                INTO has_default
                FROM information_schema.columns
                WHERE table_name = 'inventory_items'
                  AND column_name = 'id';

                IF NOT has_default THEN
                    EXECUTE 'CREATE SEQUENCE IF NOT EXISTS ' || seq_name;
                    EXECUTE 'SELECT setval(''' || seq_name || ''', COALESCE((SELECT MAX(id) FROM inventory_items), 0) + 1, false)';
                    EXECUTE 'ALTER TABLE inventory_items ALTER COLUMN id SET DEFAULT nextval(''' || seq_name || ''')';
                    EXECUTE 'ALTER SEQUENCE ' || seq_name || ' OWNED BY inventory_items.id';
                END IF;
            END IF;
        END $$;
        """)

        cur.execute("""
        CREATE INDEX IF NOT EXISTS idx_inventory_article_number
        ON inventory_items(article_number)
        """)

        cur.execute("""
        CREATE INDEX IF NOT EXISTS idx_inventory_org_article_no
        ON inventory_items(org_article_no)
        """)

        cur.execute("""
        CREATE INDEX IF NOT EXISTS idx_inventory_shelf_location
        ON inventory_items(shelf_location)
        """)

        cur.execute("""
        CREATE TABLE IF NOT EXISTS inventory_transactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            item_id BIGINT NOT NULL,
            barcode TEXT,
            action_type TEXT NOT NULL,
            qty_change INTEGER NOT NULL,
            qty_before INTEGER NOT NULL,
            qty_after INTEGER NOT NULL,
            note TEXT,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """)

        cur.execute("""
        CREATE INDEX IF NOT EXISTS idx_inventory_transactions_item_id
        ON inventory_transactions(item_id)
        """)

        cur.execute("""
        CREATE INDEX IF NOT EXISTS idx_inventory_transactions_created_at
        ON inventory_transactions(created_at DESC)
        """)

        cur.execute("""
        CREATE TABLE IF NOT EXISTS saved_views (
            name TEXT PRIMARY KEY,
            columns TEXT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP
        )
        """)

        cur.execute("""
        CREATE TABLE IF NOT EXISTS item_history (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            item_id BIGINT NOT NULL,
            field_name TEXT NOT NULL,
            old_value TEXT,
            new_value TEXT,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """)

        cur.execute("""
        CREATE INDEX IF NOT EXISTS idx_item_history_item_id
        ON item_history(item_id)
        """)

        # Sparade exportmallar (urval/kolumner/utseende som JSON-text).
        cur.execute("""
        CREATE TABLE IF NOT EXISTS export_presets (
            name TEXT PRIMARY KEY,
            settings TEXT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP
        )
        """)

    # Dessa två index kan misslyckas om det redan finns dubbletter i datan.
    # Vi vill INTE att det stoppar appen från att starta - vi försöker bara
    # skapa dem tyst, och om det inte går just nu försöker vi igen nästa
    # gång programmet startar (t.ex. efter att dubbletten städats bort).
    _try_execute(
        conn,
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_inventory_article_number_not_blank
        ON inventory_items(article_number)
        WHERE article_number IS NOT NULL AND BTRIM(article_number) <> ''
        """
    )

    _try_execute(
        conn,
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_inventory_org_article_no_not_blank
        ON inventory_items(org_article_no)
        WHERE org_article_no IS NOT NULL AND BTRIM(org_article_no) <> ''
        """
    )

    # Samma självläkande mönster som ovan: om det redan finns ett ogiltigt
    # main_category-värde i datan misslyckas detta tyst, och vi försöker
    # igen nästa gång programmet startar (t.ex. efter att datan städats).
    _try_execute(
        conn,
        """
        ALTER TABLE inventory_items
        DROP CONSTRAINT IF EXISTS chk_inventory_main_category_valid
        """
    )
    _try_execute(
        conn,
        """
        ALTER TABLE inventory_items
        ADD CONSTRAINT chk_inventory_main_category_valid
        CHECK (
            main_category IS NULL
            OR BTRIM(main_category) = ''
            OR main_category IN (
                '0. MOTOR',
                '1. BRÄNSLE/AVGASSYSTEM',
                '2. ELSYSTEM/INDIKERINGSSYSTEM',
                '3. DRIVLINA',
                '4. CHASSI',
                '5. BROMSSYSTEM',
                '6. KAROSS',
                '7. ALLMÄNNA KOMPONENTER',
                '8. VÄTSKA',
                '9. HJUL'
            )
        )
        """
    )

    _ensure_lager_tables(conn)

    conn.execute("RESET lock_timeout")


# Lagren i programmet. Varje lager har helt egna tabeller, så artiklar,
# historik och transaktioner blandas aldrig mellan dem.
#   "legacy" = det gamla lagret (artiklarna som fasas ut) - tabellerna som
#              alltid funnits, orörda.
#   "lager"  = det nya lagret.
# "number_by" styr vad Generera sätter i artikelnumret efter kategorierna:
#   "brand"    = fordonsmärke, t.ex. 5-01-MA-000001 (gamla lagret)
#   "supplier" = leverantör,   t.ex. M5-01-SMP-000001 (nya lagret)
# "number_prefix" är bokstaven som alltid sätts direkt framför huvudkategorin.
WAREHOUSES = {
    "lager": {
        "menu": "Lager",
        "title": "Momentus Lager",
        "items": "lager_items",
        "history": "lager_item_history",
        "transactions": "lager_transactions",
        "number_by": "supplier",
        "number_prefix": "M",
    },
    "legacy": {
        "menu": "Gamla lagret",
        "title": "Momentus Gamla lagret",
        "items": "inventory_items",
        "history": "item_history",
        "transactions": "inventory_transactions",
        "number_by": "brand",
        "number_prefix": "",
    },
}

_KNOWN_TABLES = {
    cfg[key] for cfg in WAREHOUSES.values() for key in ("items", "history", "transactions")
}


def _check_table(name: str) -> str:
    # Tabellnamn kan inte skickas som %s-parameter, så de sätts in i SQL-texten.
    # Därför släpps bara namn som finns i WAREHOUSES igenom.
    if name not in _KNOWN_TABLES:
        raise ValueError(f"Okänd tabell: {name}")
    return name


def _ensure_lager_tables(conn):
    """Tabellerna för det nya lagret. Samma uppbyggnad som det gamla lagrets
    tabeller, men helt fristående från dem."""
    with conn.cursor() as cur:
        cur.execute("""
        CREATE TABLE IF NOT EXISTS lager_items (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_name TEXT NOT NULL,
            main_category TEXT,
            vehicle_brand TEXT,
            product_brand TEXT,
            barcode TEXT,
            org_article_no TEXT,
            oem TEXT,
            quantity INTEGER NOT NULL DEFAULT 0,
            unit_cost DOUBLE PRECISION,
            currency TEXT,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP,
            article_number TEXT,
            shelf_location TEXT,
            last_inventory_check DATE
        )
        """)

        cur.execute("""
        CREATE INDEX IF NOT EXISTS idx_lager_items_article_number
        ON lager_items(article_number)
        """)

        cur.execute("""
        CREATE INDEX IF NOT EXISTS idx_lager_items_org_article_no
        ON lager_items(org_article_no)
        """)

        cur.execute("""
        CREATE INDEX IF NOT EXISTS idx_lager_items_shelf_location
        ON lager_items(shelf_location)
        """)

        cur.execute("""
        CREATE TABLE IF NOT EXISTS lager_transactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            item_id BIGINT NOT NULL,
            barcode TEXT,
            action_type TEXT NOT NULL,
            qty_change INTEGER NOT NULL,
            qty_before INTEGER NOT NULL,
            qty_after INTEGER NOT NULL,
            note TEXT,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """)

        cur.execute("""
        CREATE INDEX IF NOT EXISTS idx_lager_transactions_item_id
        ON lager_transactions(item_id)
        """)

        cur.execute("""
        CREATE INDEX IF NOT EXISTS idx_lager_transactions_created_at
        ON lager_transactions(created_at DESC)
        """)

        cur.execute("""
        CREATE TABLE IF NOT EXISTS lager_item_history (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            item_id BIGINT NOT NULL,
            field_name TEXT NOT NULL,
            old_value TEXT,
            new_value TEXT,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """)

        cur.execute("""
        CREATE INDEX IF NOT EXISTS idx_lager_item_history_item_id
        ON lager_item_history(item_id)
        """)

    # Samma självläkande mönster som för det gamla lagret (se ensure_schema).
    _try_execute(
        conn,
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_lager_items_article_number_not_blank
        ON lager_items(article_number)
        WHERE article_number IS NOT NULL AND BTRIM(article_number) <> ''
        """
    )

    _try_execute(
        conn,
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_lager_items_org_article_no_not_blank
        ON lager_items(org_article_no)
        WHERE org_article_no IS NOT NULL AND BTRIM(org_article_no) <> ''
        """
    )

    _try_execute(
        conn,
        """
        ALTER TABLE lager_items
        DROP CONSTRAINT IF EXISTS chk_lager_items_main_category_valid
        """
    )
    _try_execute(
        conn,
        """
        ALTER TABLE lager_items
        ADD CONSTRAINT chk_lager_items_main_category_valid
        CHECK (
            main_category IS NULL
            OR BTRIM(main_category) = ''
            OR main_category IN (
                '0. MOTOR',
                '1. BRÄNSLE/AVGASSYSTEM',
                '2. ELSYSTEM/INDIKERINGSSYSTEM',
                '3. DRIVLINA',
                '4. CHASSI',
                '5. BROMSSYSTEM',
                '6. KAROSS',
                '7. ALLMÄNNA KOMPONENTER',
                '8. VÄTSKA',
                '9. HJUL'
            )
        )
        """
    )


def _try_execute(conn, sql):
    # Anslutningen kör med autocommit, så ett misslyckat kommando lämnar
    # inget halvfärdigt efter sig - felet kan bara sväljas.
    try:
        conn.execute(sql)
    except Exception:
        pass


def find_duplicate_values(conn, column: str, table: str = "inventory_items"):
    """Hittar värden som förekommer flera gånger i en given kolumn
    (t.ex. 'org_article_no' eller 'article_number'), utan att ändra något.
    Returnerar en lista av dicts: [{"value": ..., "count": ..., "ids": [...]}]
    """
    if column not in ("org_article_no", "article_number"):
        raise ValueError("Ogiltig kolumn för dubblettkontroll.")

    query = f"""
        SELECT BTRIM({column}) AS value, COUNT(*) AS cnt, ARRAY_AGG(id ORDER BY id) AS ids
        FROM {_check_table(table)}
        WHERE {column} IS NOT NULL AND BTRIM({column}) <> ''
        GROUP BY BTRIM({column})
        HAVING COUNT(*) > 1
        ORDER BY value
    """

    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(query)
        rows = cur.fetchall()

    return [{"value": r["value"], "count": r["cnt"], "ids": r["ids"]} for r in rows]


def load_saved_views(conn):
    """Returnerar alla sparade vyer som en lista av dicts: [{"name": ..., "columns": [...]}]"""
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute("SELECT name, columns FROM saved_views ORDER BY name")
        rows = cur.fetchall()
    return [{"name": r["name"], "columns": r["columns"].split(",") if r["columns"] else []} for r in rows]


def save_view(conn, name: str, column_keys: list):
    columns_csv = ",".join(column_keys)
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO saved_views (name, columns, updated_at)
            VALUES (%s, %s, CURRENT_TIMESTAMP)
            ON CONFLICT (name) DO UPDATE
            SET columns = EXCLUDED.columns,
                updated_at = CURRENT_TIMESTAMP
            """,
            (name, columns_csv)
        )


def delete_view(conn, name: str):
    with conn.cursor() as cur:
        cur.execute("DELETE FROM saved_views WHERE name = %s", (name,))


def load_export_presets(conn):
    """Returnerar [(name, settings_json), ...] sorterat på namn."""
    with conn.cursor(row_factory=tuple_row) as cur:
        cur.execute("SELECT name, settings FROM export_presets ORDER BY name")
        return [(r[0], r[1]) for r in cur.fetchall()]


def save_export_preset(conn, name: str, settings_json: str):
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO export_presets (name, settings, updated_at)
            VALUES (%s, %s, CURRENT_TIMESTAMP)
            ON CONFLICT (name) DO UPDATE
            SET settings = EXCLUDED.settings,
                updated_at = CURRENT_TIMESTAMP
            """,
            (name, settings_json)
        )


def delete_export_preset(conn, name: str):
    with conn.cursor() as cur:
        cur.execute("DELETE FROM export_presets WHERE name = %s", (name,))


# Samma 3-bokstavskoder som används i Artikelnummer Generatorn, tillgängliga
# härifrån så att andra delar av programmet (t.ex. Lager) kan generera
# artikelnummer utan att duplicera logiken på fler ställen.
ARTICLE_NUMBER_BRANDS = [
    ("VO", "Volvo"),
    ("SC", "Scania"),
    ("MA", "MAN"),
    ("ME", "Mercedes"),
    ("DA", "DAF"),
    ("RE", "Renault"),
    ("IV", "Iveco"),
]


# Leverantörskoder för artikelnummer i det nya lagret: (kod, namn).
# Ny leverantör = lägg till en rad här. Den första är förvald i editorn.
ARTICLE_NUMBER_SUPPLIERS = [
    ("SMP", "SAMPA"),
]


def _extract_seq_from_article(article_number: str) -> int:
    try:
        return int(article_number.rsplit("-", 1)[1])
    except Exception:
        return 0


def _find_first_free_sequence(used_article_numbers, last_value: int) -> int:
    used_set = set()

    for article_number in used_article_numbers:
        seq = _extract_seq_from_article(article_number)
        if seq > 0:
            used_set.add(seq)

    for seq in range(1, last_value + 1):
        if seq not in used_set:
            return seq

    return last_value + 1


def generate_article_number(conn, k: str, uu: str, mmm: str) -> str:
    prefix = f"{k}-{uu}-{mmm}"

    # Allt nedan sker i en transaktion: FOR UPDATE-låset på countern hålls
    # tills blocket är klart, så två användare kan inte få samma nummer.
    # Vid fel rullas allt tillbaka automatiskt och felet skickas vidare.
    with conn.transaction():
        with conn.cursor(row_factory=tuple_row) as cur:
            cur.execute("""
            INSERT INTO counters(prefix, last)
            VALUES (%s, %s)
            ON CONFLICT (prefix) DO NOTHING
            """, (prefix, 0))

            cur.execute("""
            SELECT last
            FROM counters
            WHERE prefix = %s
            FOR UPDATE
            """, (prefix,))
            row = cur.fetchone()

            if not row:
                raise ValueError(f"Kunde inte låsa counter för prefix {prefix}.")

            last_value = int(row[0])

            cur.execute("""
            SELECT article_number
            FROM used_numbers
            WHERE prefix = %s
            ORDER BY article_number
            """, (prefix,))
            used_rows = cur.fetchall()
            used_article_numbers = [r[0] for r in used_rows]

            next_seq = _find_first_free_sequence(used_article_numbers, last_value)

            if next_seq > 999999:
                raise ValueError("Slut på löpnummer för denna kombination.")

            candidate = f"{prefix}-{next_seq:06d}"

            cur.execute("""
            INSERT INTO used_numbers(article_number, prefix)
            VALUES (%s, %s)
            """, (candidate, prefix))

            cur.execute("""
            UPDATE counters
            SET last = GREATEST(last, %s)
            WHERE prefix = %s
            """, (next_seq, prefix))

    return candidate


def log_item_changes(conn, item_id: int, changes: list, table: str = "item_history"):
    """changes: lista av (field_name, old_value, new_value)-tupler.
    Loggar bara faktiska ändringar - anropas med redan filtrerad lista.

    Committar inte själv: anropas antingen under autocommit (en sats = en
    transaktion) eller inuti ett "with conn.transaction()"-block som hör
    ihop med skrivningen av själva artikeln."""
    if not changes:
        return

    with conn.cursor(row_factory=tuple_row) as cur:
        cur.executemany(
            f"""
            INSERT INTO {_check_table(table)} (item_id, field_name, old_value, new_value)
            VALUES (%s, %s, %s, %s)
            """,
            [(item_id, field, old, new) for field, old, new in changes]
        )


def get_item_history(conn, item_id: int, table: str = "item_history"):
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            f"""
            SELECT
                id,
                field_name,
                old_value,
                new_value,
                -- Kolumnen är TIMESTAMP utan tidszon och fylls av servern med
                -- CURRENT_TIMESTAMP i serverns tidszon. Här tolkas värdet tillbaka
                -- till en tidszonsmedveten tid så att klienten kan visa lokal tid.
                -- Inget i tabellen ändras.
                created_at AT TIME ZONE current_setting('TimeZone') AS created_at
            FROM {_check_table(table)}
            WHERE item_id = %s
            ORDER BY created_at DESC, id DESC
            """,
            (item_id,)
        )
        return cur.fetchall()


def delete_history_entry(conn, history_id: int, table: str = "item_history"):
    with conn.cursor() as cur:
        cur.execute(f"DELETE FROM {_check_table(table)} WHERE id = %s", (history_id,))
